# Generated by Django 4.2.6 on 2023-11-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicArchive', '0002_alter_song_album_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicArchive.album'),
        ),
    ]
