# Generated by Django 4.2.6 on 2023-11-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicArchive', '0003_alter_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
    ]
