# Generated by Django 4.2.6 on 2023-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicArchive', '0009_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='song_images/'),
        ),
    ]
