# Generated by Django 4.2.6 on 2023-12-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicArchive', '0010_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='albums', to='MusicArchive.song'),
        ),
    ]
