# Generated by Django 4.2.6 on 2023-11-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigmanager', '0002_sitio_aforo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='integrante',
            new_name='lider',
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigmanager.grupo')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigmanager.musico')),
            ],
        ),
    ]
