# Generated by Django 4.2.6 on 2023-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigmanager', '0003_rename_integrante_grupo_lider_integrante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='lider',
        ),
        migrations.AddField(
            model_name='grupo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitio',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Integrante',
        ),
    ]
