# Generated by Django 4.2.6 on 2023-11-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigmanager', '0004_remove_grupo_lider_grupo_descripcion_sitio_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gigmanager.grupo'),
        ),
    ]
