# Generated by Django 4.2.6 on 2023-11-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigmanager', '0005_musico_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musico',
            name='grupo',
        ),
        migrations.AddField(
            model_name='grupo',
            name='integrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gigmanager.musico'),
        ),
    ]
